doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 'mariadb-10.11.2'
        profiling_collect_backtrace: '%kernel.debug%'
        default_table_options:
            charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/User/Entity'
                prefix: 'App\Modules\User\Entity'
                alias: App
            Student:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Student/Entity'
                prefix: 'App\Modules\Student\Entity'
                alias: App
            Teacher:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Teacher/Entity'
                prefix: 'App\Modules\Teacher\Entity'
                alias: App
            ClassRoom:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/ClassRoom/Entity'
                prefix: 'App\Modules\ClassRoom\Entity'
                alias: App
            Subject:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Subject/Entity'
                prefix: 'App\Modules\Subject\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
