nelmio_api_doc:
    documentation:

        info:
            title: School management system
            description: School management system
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
