nelmio_api_doc:
    documentation:
        info:
            title: School management system
            description: School management system
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
