security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            id: App\Modules\User\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/v1/user/login
            stateless: true
            provider: user_provider
            json_login:
                check_path: /api/v1/user/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/v1
            stateless: true
            jwt: ~


#    access_control:
#        - { path: ^/api/v1/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_USER: ~
        ROLE_STUDENT: ROLE_USER
        ROLE_TEACHER: ROLE_STUDENT
        ROLE_ADMIN: ROLE_TEACHER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
