services:

  server:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: 'php'
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    restart: 'on-failure'
    tty: true
    volumes:
      - .:/var/www
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - database
      - mailpit
    ports:
      - '80:80'

  database:
    image: mariadb:10.11.2
    container_name: 'database'
    restart: 'on-failure'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'school-management-system'
      MYSQL_USER: 'jakubgawor'
      MYSQL_PASSWORD: 'jakubgawor'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'

  mailpit:
    image: axllent/mailpit
    container_name: 'mailpit'
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mysql_data: