App\Modules\User\Request\V1\ChangeForgottenPassword:
  properties:
    email:
      - Email:
          message: 'VALIDATION.EMAIL_NOT_VALID'
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 64
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    password:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    repeatPassword:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    token:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 8
          max: 8
          exactMessage: 'VALIDATION.INVALID_TOKEN_LENGTH'
