App\Modules\User\Request\V1\ChangeUserPassword:
  properties:
    currentPassword:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    newPassword:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    newPasswordConfirmation:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
