App\Modules\Subject\Request\V1\CreateSubject:
  properties:
    teacherId:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Regex:
          pattern: '/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i'
          message: 'VALIDATION.INVALID_FORMAT'
    name:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 255
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'
    description:
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          max: 4096
          maxMessage: 'VALIDATION.TOO_LONG'