App\Modules\User\Request\V1\RequestPasswordChange:
  properties:
    email:
      - NotBlank:
          message: 'VALIDATION.MISSING'
      - Type:
          type: string
          message: 'VALIDATION.INVALID_FORMAT'
      - Length:
          min: 3
          max: 64
          minMessage: 'VALIDATION.TOO_SHORT'
          maxMessage: 'VALIDATION.TOO_LONG'