user:
    resource:
        path: ../src/Modules/User/Controller/
        namespace: App\Modules\User\Controller
    type: attribute

class_room:
    resource:
        path: ../src/Modules/ClassRoom/Controller/
        namespace: App\Modules\ClassRoom\Controller
    type: attribute

student:
    resource:
        path: ../src/Modules/Student/Controller/
        namespace: App\Modules\Student\Controller
    type: attribute

teacher:
    resource:
        path: ../src/Modules/Teacher/Controller/
        namespace: App\Modules\Teacher\Controller
    type: attribute

subject:
    resource:
        path: ../src/Modules/Subject/Controller/
        namespace: App\Modules\Subject\Controller
    type: attribute

grade:
    resource:
        path: ../src/Modules/Grade/Controller/
        namespace: App\Modules\Grade\Controller
    type: attribute

announcement:
    resource:
        path: ../src/Modules/Announcement/Controller/
        namespace: App\Modules\Announcement\Controller
    type: attribute
