services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Modules/User/Entity/'
            - '../src/Kernel.php'

    App\Shared\Listener\ExceptionListener:
        arguments:
            $environment: "%kernel.environment%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }