services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Modules/User/Entity/'
            - '../src/Kernel.php'

    App\Shared\Listener\ExceptionListener:
        arguments:
            $environment: "%kernel.environment%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Modules\User\EventListener\JwtNotFoundListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJwtNotFound }

    App\Modules\User\EventListener\JwtInvalidListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onInvalidJwt }

    App\Modules\User\EventListener\JwtExpiredListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onExpiredJwt }

    App\Modules\User\EventListener\VerifyUserListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: isUserVerified }

    App\Modules\Student\EventListener\StudentAddedToClassRoomListener:
        tags:
            - { name: kernel.event_listener, event: App\Modules\ClassRoom\Event\StudentAddedToClassRoom, method: onStudentAddedToClassRoom }

    App\Modules\Student\EventListener\RemovedClassRoomListener:
        tags:
            - { name: kernel.event_listener, event: App\Modules\ClassRoom\Event\ClassRoomRemoved, method: onClassRoomRemoved }

    _instanceof:
        App\Shared\Command\Sync\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: command.sync.bus }
        App\Shared\Command\Async\CommandHandler:
            tags:
                - { name: 'messenger.message_handler', bus: command.async.bus }